issues:
        exclude-rules:
                # Ignore govet.lostcancel in integration test files. The
                # integration tests make substantial use of context.WithTimeout()
                # without corresponding cancel() calls, which trigger this. So
                # disable these warnings for now until this is fixed upstream
                # (otherwise merging upstream itest changes will become 
                # significantly harder)
                - path: lntest/
                  text: lostcancel

                # Exclude gosec from running for tests so that tests with weak randomness
                # (math/rand) will pass the linter.
                - path: _test\.go
                  linters:
                    - gosec

run:
  deadline: 10m

linters:
  skip-files: "mobile\\/.*generated\\.go"

  disable-all: true
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - errchkjson
    - exportloopref
    - gofmt
    - gosimple
    - govet
    - grouper
    - ineffassign
    - nosprintfhostport
    - reassign
    - rowserrcheck
    - typecheck
    - unconvert
    - unused
    - vetshadow
