name: Docker Build
on: [push, pull_request]
permissions:
  contents: read

jobs:
  build:
    name: Dockerfile build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac #v4.0.0
      - name: Build the Docker image
        run: docker build -t decred/dcrlnd:$(date +%s) .

# Commented out as it needs updating.
#  compose:
#    name: Compose build
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab #v3.5.2
#      - name: Build docker compose file
#        working-directory: ./docker
#        run: docker-compose build
