name: Fuzz CI

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "*"

defaults:
  run:
    shell: bash

env:
  GOCACHE: /home/runner/work/go/pkg/build
  GOPATH: /home/runner/work/go
  DOWNLOAD_CACHE: /home/runner/work/download_cache
  BITCOIN_VERSION: 0.19.1
  GO_VERSION: 1.14.4

jobs:
  ########################
  # Fuzz check
  ########################
  fuzz-check:
    name: Fuzz check
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v2

      - name: build fuzz
        run:  ./scripts/run_fuzzers.sh
